name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.0'

    - name: Build for multiple platforms
      run: |
        mkdir -p build
        GOOS=linux GOARCH=amd64 go build -v -o build/pw_maker_linux_amd64 ./pw_maker
        GOOS=darwin GOARCH=amd64 go build -v -o build/pw_maker_darwin_amd64 ./pw_maker
        GOOS=windows GOARCH=amd64 go build -v -o build/pw_maker_windows_amd64.exe ./pw_maker

    - name: Bump version and push tag
      id: tag_version
      uses: anothrNick/github-tag-action@1.61.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        WITH_V: true

    - name: Generate changelog
      id: changelog
      uses: mikepenz/release-changelog-builder-action@v3
      with:
        configuration: "changelog-config.json"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: false
        files: |
          build/pw_maker_linux_amd64
          build/pw_maker_darwin_amd64
          build/pw_maker_windows_amd64.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
